plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.14'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.nuro'
version = '0.0.1-SNAPSHOT'
description = 'nuro - AI skin diagnosis backend'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.ai:spring-ai-bom:1.1.0"
    }
}

dependencies {
    // Web
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // JPA
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // Validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // AOP
    implementation 'org.springframework.boot:spring-boot-starter-aop'

    // Actuator
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    // WebFlux
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

    // Spring AI - Gemini
    implementation 'org.springframework.ai:spring-ai-starter-model-google-genai'
    // Spring AI - Anthropic Claude
    implementation 'org.springframework.ai:spring-ai-starter-model-anthropic'

    // AWS S3
    implementation 'software.amazon.awssdk:s3:2.39.2'

    // Swagger / OpenAPI
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.9'

    // .env 자동 로드
    implementation 'me.paulschwarz:spring-dotenv:4.0.0'

    // PostgreSQL (운영)
    runtimeOnly 'org.postgresql:postgresql'

    // H2 (로컬/테스트용)
    runtimeOnly 'com.h2database:h2'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Devtools
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    //nanoid
    implementation 'com.aventrix.jnanoid:jnanoid:2.0.0'

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}